
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES  * B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES S
LEFT JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID
LEFT JOIN AUTHOR A
ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE DATE_FORMAT(SALES_DATE, "%Y-%m") = '2022-01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC
