-- 코드를 작성해주세요
SELECT INFO.ITEM_ID,
ITEM_NAME,
RARITY
FROM ITEM_INFO AS INFO
JOIN ITEM_TREE AS TREE
ON TREE.ITEM_ID = INFO.ITEM_ID
WHERE TREE.PARENT_ITEM_ID IN 
(SELECT ITEM_INFO.ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY INFO.ITEM_ID DESC