-- 코드를 작성해주세요
SELECT C.ID, B.FISH_NAME, A.MAX_LENGTH LENGTH
FROM (
        SELECT FISH_TYPE, MAX(LENGTH) MAX_LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    ) A
JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE
JOIN FISH_INFO C
ON C.LENGTH = A.MAX_LENGTH AND A.FISH_TYPE = C.FISH_TYPE
ORDER BY C.ID