# 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회하는 SQL문을 작성해주세요
SELECT BOARD.TITLE, BOARD.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, 
DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD BOARD
JOIN USED_GOODS_REPLY REPLY ON BOARD.BOARD_ID = REPLY.BOARD_ID 
WHERE DATE_FORMAT(BOARD.CREATED_DATE,'%Y-%m') = '2022-10'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE;